---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Release Drafter

on:
  workflow_call:

permissions:
  contents: write
  statuses: write
  packages: read

jobs:
  Draft:
    uses: ivuorinen/.github/.github/workflows/sync-labels.yml@main
    permissions:
      contents: write
      statuses: write
      packages: read

