---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Stale

on:
  schedule:
    - cron: '0 8 * * *'
  workflow_call:
  workflow_dispatch:

permissions:
  packages: read
  statuses: read

jobs:
  stale:
    uses: ivuorinen/.github/.github/workflows/stale.yml@main
    permissions:
      contents: write # only for delete-branch option
      issues: write
      pull-requests: write
      statuses: read
      packages: read

